services:
  onemap:
    environment:
    volumes:
      - type: bind
        source: .
        target: /onemap
      - type: bind
        source: ${HM3D_PATH:-/dev/null}
        target: /onemap/datasets/versioned_data
        read_only: true
